### ISSUE TITLE
Warning while replacing NA with 0

### ISSUE THREAD

**Issue by umbersar** [umbersar/sites_ml#8]
This code gives a warning:
Warning message:
In `[<-.factor`(`*tmp*`, thisvar, value = 0) :
  invalid factor level, NA generated

https://github.com/umbersar/sites_ml/blob/4312b96b48606c7961fbffc5154d3dccbd66f395/soil.r#L69

**Comment by zaynxalic** [comment]
I don't know why I did not get any problem in executing that line

**Comment by umbersar** [comment]
seems to work for me now. Not sure what happened there. Will close the issue for now but keep an eye out for it if it resurfaces in future.
